environment:
  matrix:
  - LUA: "lua 5.1"
  - LUA: "lua 5.2"
  - LUA: "lua 5.3"
  - LUA: "luajit 2.0"
  - LUA: "luajit 2.1"

before_build:
  - set PATH=C:\Python27\Scripts;%PATH% # Add directory containing 'pip' to PATH
  - pip install hererocks
  - hererocks env --%LUA% -rlatest
  - call env\bin\activate
  - lua -v
  - luarocks --version
  - luarocks install penlight

build_script:
  - luarocks make

test_script:
  - lua test.lua
